import type { Metadata } from "next";
import "./../styles/global.css";
import { Noto_Sans } from "next/font/google";

const noto_sans = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "RoProject-dev",
  description: "Generated by Ro",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
